### ISSUE TITLE
Post fails (receiving corrupted data)

### ISSUE THREAD

**Issue by amgad-naiem** [JuliaWeb/Morsel.jl#16]
Post fails when receiving large POST data remotely. This cannot be replicated when both the server and the client are running on the same machine.

The following gist code replicates the problem.
https://gist.github.com/amgad-naiem/a73ae8cffb6ea0ced612

The error is unexpected characters in the received POST data
```
ErrorException("Unknown value\nLine: 0\nAround: ...test539\":�\x16\0\0\0\0\0\0\"data 539\",\"t...\n                    ^\n")
ERROR: Unknown value
Line: 0
Around: ...test539":?"data 539","t...
```

**Comment by sbromberger** [comment]
I can't reproduce this problem: server running Ubuntu 14.04, Julia Version 0.3.5 (2015-01-08 22:33 UTC), client is Safari on OSX getting /runTest. The GET results in a popup javascript alert saying everything went ok.

**Comment by mbeltagy** [comment]
I verify that the problem seems to be gone now. I tested on an Ubuntu server identical to @sbromberger.

**Comment by amgad-naiem** [comment]
Yes. the issue is fixed in the new Julia / Morsel releases
