### ISSUE TITLE
signal (11): Segmentation fault

### ISSUE THREAD

**Issue by jne555** [JuliaWeb/Morsel.jl#33]
I'm using a 64-bit RedHat 6.5 server running the latest stable release of Julia 3.5 and am getting a seg fault error trying to use morsel.

I enter the following into the Julia REPL:

using Morsel
app = Morsel.app()
get(app, "/about") do req, res
    "This app is running on Morsel"
end

start(app, 8000)

Then in another terminal I run the following curl command:

curl http://localhost:8000/about

Which results in this error recieved on the server:

signal (11): Segmentation fault
memcpy at /lib64/libc.so.6 (unknown line)
write at /usr/bin/../lib64/julia/sys.so (unknown line)
unknown function (ip: 936587280)
Memory fault(coredump)

Joel

**Comment by jne555** [comment]
The issue was found to be with HttParser and more specifically the shared library libhttp-parser. In the deps.jl file under HttpParser the @checked_lib was pointing to /usr/lib64/libhttp_parser.so. However, our libhttp_parser.so in lib64 had a symbolic link to libhttp_parser.so.2.0. We figured we were running into an issue with the versions of libhttp_parser, so we decided to manually build libhttp_parser following the steps in build.jl and update the @checked_lib within deps.jl to point to the libhttp_parser.so under HttpParser/deps/usr/lib. After making those updates we were able to run morsel as expected.

**Comment by nalimilan** [comment]
Indeed, distribution packages never ship unversioned .so files, only the .so.2.0 version: you need to install -devel packages for the former. Looks like HttpParser should use the .so.2.0 file, it would also make it easier to handle ABI breaks and parallel installation of different versions.

**Comment by IainNZ** [comment]
I don't quite understand whats happening/what should change, but could you please say all of that again at https://github.com/JuliaWeb/HttpParser.jl/issues so it gets fixed?
