### ISSUE TITLE
Link to a data science example in the docs?

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/Morsel.jl#36]
Hi there,

[Here](https://bitbucket.org/jocklawrie/skeleton-webapp.jl) is an example that uses Morsel for data science.
If it helps, feel free to link to it from Morsel's readme, or otherwise use as you please. E.g., create an examples folder and place the entire repo in there.

Cheers,
Jock

**Comment by IainNZ** [comment]
Please submit a pull request to README describing it in your own words, I'll merge it.
