### ISSUE TITLE
Update routes after running

### ISSUE THREAD

**Issue by lilinjn** [JuliaWeb/Morsel.jl#38]
Hi -- Is it possible to update a route after the server is running? 
If I begin with:
````
app = Morsel.app()

get(app, "/test") do req, res
    "Original"
end

@async start(app, 8000)
````

And then later on in the repl session:
````
get(app, "/test") do req, res
    "Updatedl"
end
````

Getting `/test` always returns `Original`

Fyi, having the route handler call a global function and updating the global function in the repl works just fine e.g.

````
foo(req,res) = "bar"

get(app, "/test") do req, res
   foo(req,res)
end

##later 
foo(req,res) = "baz"
````

Also adding completely different routes after the server is started works fine as well -- perhaps there is some tweaking needed in the route tree logic?

thanks!

**Comment by yfractal** [comment]
@lilinjn 
I have sent a [pull request](https://github.com/JuliaWeb/Morsel.jl/pull/39) for this issue, it works fine in my local.

**Comment by lilinjn** [comment]
Thanks!
