### ISSUE TITLE
Web server?

### ISSUE THREAD

**Issue by philipithomas** [JuliaWeb/Morsel.jl#40]
Just a quick question that I think should be included in the README - 

Is the built-in webserver production-grade / threadsafe? Or, should we be looking at something like nginx in front of Morsel?

**Comment by IainNZ** [comment]
What do you mean by built-in websever? HttpServer.jl? Julia isn't multithreaded, and HttpServer so isn't multithreaded (in fact, its extremely like Node.js, single process with things done async, and uses libuv underneath). If you were to use it seriously/at scale, it'd need a load balancer in front of it I suppose at a certain point.

Production-grade? Ehhhh... I don't know how hard anyone has pushed this stuff, very hard to say when and how it would fall over.

**Comment by IainNZ** [comment]
If I was to use Julia for a web-based app, I'd write everything public facing in another language, and then put all my computational work in Julia behind some sort of queue, hit it just over plain HTTP because it'd be internal.

**Comment by philipithomas** [comment]
Ok, thanks. So good enough to run health checks against HttpServer.jl, but not good enough for sustained traffic.

**Comment by IainNZ** [comment]
I'd mainly be worried about long-run behaviour, like memory problems. Also the HTTPS stuff doesn't inspire confidence.
